### ISSUE TITLE
20130902

### ISSUE THREAD

**Issue by tristones** [tristones/branson#1]
1.root账号，可以list所有用户，和管理所有模块的全部数据。
2.提供或者固化一组测试用user数据，包括role是manager,trainer,user的用户各一个。
3.add new course中，提供target audience，Objective的普通文本输入框，Course Content提供富文本编辑器。Duration和Class Size直接从最新一次open course中抓取。
4.保证course部分的list，add，edit，del等的功能都是正常可用的
5.HR information和Users的左侧menu，不需要展开。点击就打开相应list页面。Add news功能放在list page的右上角。类似Course list页面。
6.HR information的list,如果点击Delete,该条目就不要在list显示了。Status应该是Del,区别与Show和Hide

**Comment by codinghero** [comment]
1，2，3，5，6已经完成
