### ISSUE TITLE
statistics report / by month 增加一列Total Training Hour

### ISSUE THREAD

**Issue by tristones** [tristones/branson#103]
statistics report / by month 增加一列Total Training Hour,就是把detail里显示的该月的每个课程的Training Hours(total)值加总一下。

![image](https://f.cloud.github.com/assets/351457/2393482/e22acbb0-a992-11e3-8025-1d145864ddda.png)

**Comment by codinghero** [comment]
这个你已经改成了total participant，还要改吗？
