### ISSUE TITLE
【优先】前台manager的列表中，可以点击Course name看到该课程具体情况。

### ISSUE THREAD

**Issue by tristones** [tristones/branson#121]
前台manager的列表中，可以点击Course name弹出窗口，看到该课程情况，即显示上课人员名，课程名称，上课时间，地点。

![image](https://cloud.githubusercontent.com/assets/351457/2691835/afccb8de-c38e-11e3-8879-9fa94faaee43.png)

**Comment by codinghero** [comment]
显示上课人员名是指显示trainer?还是所有上课的学生
