### ISSUE TITLE
增加新开课程是，增加一个Location选项菜单。

### ISSUE THREAD

**Issue by tristones** [tristones/branson#122]
1.增加新开课程是，增加一个Location选项菜单。具体包括哪几个地区待确认。
2.前台的相应的课程的detail也要显示Location了。

![image](https://cloud.githubusercontent.com/assets/351457/2691849/2e07f5b0-c38f-11e3-9b3c-dfb7403d3f60.png)

**Comment by codinghero** [comment]
把Location 给我一下
