### ISSUE TITLE
没有按ready to go的课程，在output report 中不要输出统计数据。

### ISSUE THREAD

**Issue by tristones** [tristones/branson#123]
1.所有被HR或者manager否决的申请人，都不要输出到output report中。

2.如下图所示，5月课程还没有ready to go,所以不要输出统计到output report.
![image](https://cloud.githubusercontent.com/assets/351457/2727612/32293120-c5da-11e3-8221-04f5140e2bb0.png)

**Comment by codinghero** [comment]
fixed
