### ISSUE TITLE
open courses后，会有db写入错误

### ISSUE THREAD

**Issue by tristones** [tristones/branson#126]
open courses后，会有db写入错误。但是课程实际已经开好了。

![image001](https://cloud.githubusercontent.com/assets/351457/2911092/cad83b76-d653-11e3-9591-ec1a21fecbea.png)

**Comment by codinghero** [comment]
![image](https://cloud.githubusercontent.com/assets/1644594/2911136/d66bb962-d654-11e3-9013-2d2a3e224b1c.png)

**Comment by codinghero** [comment]
可能是web.config中没有配置开课提醒的邮件模板没有配置好

**Comment by codinghero** [comment]
检查web.config里面有没有MAILAddSessionTrainer项
