### ISSUE TITLE
添加功能：根据用户提供的user list excel文件，直接导入数据库

### ISSUE THREAD

**Issue by tristones** [tristones/branson#14]

**Comment by codinghero** [comment]
需要定下导入的用户excel 格式，目前做下来有几个问题：
1.location、department信息在导入之前必须保证已经添加完整
2.需要提供一套account用户名生成规范，可以借用email,但必须保证email字段填写完整且不重复
3.由于可能存在manager 同名的情况，所以最好能提供manager 唯一的id,如果不能则不提供manager字段导入
综上，可以稳定导入的信息如下：
Employee  Number,Chinese Name,English Name,Department,Title,Email,Location
所以我建议只提供如上字段的用户信息导入，其他信息手工在后台补全。

**Comment by tristones** [comment]
该功能不提供给用户，现在xls增加了line manager email一栏，先导入符合规范的有效数据。

**Comment by codinghero** [comment]
我已经导了一批用户，但是没有导入manager 信息
