### ISSUE TITLE
self learning 流程整理

### ISSUE THREAD

**Issue by tristones** [tristones/branson#140]
用户前台申请课程，
1.选择自习日期。
2.选择时段：时段分为A （9-11点），或者B （14-16点）。该时段仅记录，实际登录，只要是当天都可以。
3.每天名额限制为5人（web.config参数？）
ps:名额的计算方式是非否决的申请都算一个名额
4.提交申请后发送通知邮件给主管。

主管审核
1.主管收到邮件通知，点击链接登录到前台的Manager位置。self learning的可能能否跟其他类型课程有一个区别？
2.查看相应申请，包括主管可以了解到，申请人，课程名，时长，上课日期，上课时段。
3.批准或者否决的申请。
4.发送批准或者否决通知邮件给用户。

HR审核
1.如果主管审核通过，HR在后台可以看到相应已批准申请（包括未批准申请也显示，否决的申请不用显示在pending里）。
2.HR批准或者否决申请。
3.如果批准通过，发送通知邮件给用户和主管
4.如果批准拒绝，发送通知邮件给用户。

HR日常工作
1.检查每天的申请
2.打印当天的自习出勤表，供相应用户签字
3.自习结束过，为相应用户更新该课程出勤状态（present,absent,asf for leave）

用户申请通过后的上课流程
1.到自习室签到HR打印的出勤表
2.用自己账号登录系统
3.打开相应课程开始自习。（系统记录start learning时间）
4.结束课程（如果能有记录结束时间更好）

Self Learning的统计
1.自习的统计作为单独分类，相应各个统计表中，多加一项 self learning

**Comment by codinghero** [comment]
![emerson self learning progress](https://cloud.githubusercontent.com/assets/1644594/3489530/9deee240-0533-11e4-8552-11032a4d6925.png)

**Comment by tristones** [comment]
问：自习课程也需要打印出勤表？
答：是，自习课程的出勤表是打印一张当天的申请人出勤表，供相关申请自习学员在自习室签到记录用。

用户申请通过后的上课流程，指的是下面4步。

![image](https://cloud.githubusercontent.com/assets/351457/3581309/84e2cc50-0be9-11e4-8d20-70a9bc8d21c0.png)

4.结束课程如果不好记录
解决：是否可以以点击视频，或者点击start learning链接作为已经自习过的依据。
