### ISSUE TITLE
statistics report / by user 点击用户的detail页，没有完成的课程也显示出来了。

### ISSUE THREAD

**Issue by tristones** [tristones/branson#146]
statistics report / by user 点击用户的detail页，没有完成的课程也显示出来并计入总数了。需要去掉。

![image](https://cloud.githubusercontent.com/assets/351457/3407355/ba2f2c72-fda8-11e3-9cad-e567ab644009.png)

**Comment by codinghero** [comment]
有个更严格的过滤条件 每个课程的学习记录都有finishdate 只要finishdate在当前时间之前的都算完成，但是我发现现在客户在使用时都没有上传结业记录，所以这个条件不能用上
