### ISSUE TITLE
前台self leaning apply申请了课程，后台SL- pending application中没出现

### ISSUE THREAD

**Issue by tristones** [tristones/branson#150]
前台self leaning apply申请了课程，后台SL- pending application中没出现

![image005](https://cloud.githubusercontent.com/assets/351457/3596024/8d06baf6-0cbe-11e4-95a2-dbdcafabcf51.jpg)

![image](https://cloud.githubusercontent.com/assets/351457/3596030/9ae2b512-0cbe-11e4-95f8-8572a5c4e952.png)

**Comment by tristones** [comment]
我修改了 GetAllEnrollmentUnHRAuditSelfLearning中的方法，默认查询Manager应该是0值。现在可以查询出数据了。

**Comment by codinghero** [comment]
我回去check一下

**Comment by codinghero** [comment]
self learning 之前不是说manager 批准过了才到后台hr这里吗？只有manager approve过的才会显示再hr后台
