### ISSUE TITLE
前台self leaning选择时段的问题

### ISSUE THREAD

**Issue by tristones** [tristones/branson#151]
前台用户选择自习时段区域，是否可以是两个单选框，选择 上午(9-11点） 或者 下午（14-16点）。

![image](https://cloud.githubusercontent.com/assets/351457/3596051/d44c2cb6-0cbe-11e4-90ac-49452d436eeb.png)

![image](https://cloud.githubusercontent.com/assets/351457/3596067/11bf2c24-0cbf-11e4-9393-239c24228918.png)

**Comment by codinghero** [comment]
![screen shot 2014-08-04 at 11 38 19](https://cloud.githubusercontent.com/assets/1644594/3799365/8d06b91e-1bed-11e4-8eaf-48a3e04862c4.png) 

fixed
