### ISSUE TITLE
Our manager reported that, they cannot approve the application

### ISSUE THREAD

**Issue by tristones** [tristones/branson#152]
Manager 不能在前台approve下属的申请。

![image003](https://cloud.githubusercontent.com/assets/351457/3652455/ede1e3d8-113b-11e4-9daa-a2c2846a4017.png)

![image001](https://cloud.githubusercontent.com/assets/351457/3652456/f6d1355c-113b-11e4-8932-ae77fb78b778.png)

![image002](https://cloud.githubusercontent.com/assets/351457/3652458/fbe464ec-113b-11e4-8d96-abbea8184196.png)

**Comment by tristones** [comment]
目前测试结果是，如果这个manager下面，有需要审核的申请，列表就会失败。

**Comment by codinghero** [comment]
修复
