### ISSUE TITLE
后台 Schedule Courses / edit course / add user 功能在IE中异常

### ISSUE THREAD

**Issue by tristones** [tristones/branson#155]
IE不能正常添加新用户。下图的safari中正常。

![image](https://cloud.githubusercontent.com/assets/351457/3669943/16ab7692-123d-11e4-8f55-bb31f79f2e19.png)

IE中点击Add后，出现false字样

![image](https://cloud.githubusercontent.com/assets/351457/3669998/1207806c-123e-11e4-892b-5b2b8688a119.png)

**Comment by codinghero** [comment]
修复
