### ISSUE TITLE
新注册用户，注册成功后，发送通知邮件给管理员。或者通过其他办法通知管理员。【测试发送不成功】

### ISSUE THREAD

**Issue by tristones** [tristones/branson#171]
新注册用户，注册成功后，发送通知邮件给管理员。或者通过其他办法通知管理员。

**Comment by tristones** [comment]
这个他们回馈说，不成功。管理员没有收到邮件。你检查看看是否有bug。

**Comment by codinghero** [comment]
![image](https://cloud.githubusercontent.com/assets/1644594/4967503/74969848-6816-11e4-8ef1-9f6c3fd5231b.png)

在web.config 里面添加ADMINEmail设置系统管理员邮箱，接受注册邮件
`
    <add key="ADMINEmail" value="guest@XXX"/>
`
