### ISSUE TITLE
用户所属地区增加Malaysia / Japan / Korea 三个地区。

### ISSUE THREAD

**Issue by tristones** [tristones/branson#187]
![image](https://cloud.githubusercontent.com/assets/351457/4730518/0b6c66ce-599b-11e4-8001-bbdf57c6826a.png)

**Comment by tristones** [comment]
执行了update sql以后，候选列表中还是没有这三个地区。

![791fabb3-b644-497c-8088-22bdd3d2182f](https://cloud.githubusercontent.com/assets/351457/4856789/8bc9588a-60c2-11e4-810c-7e45f0338ea4.jpg)

**Comment by codinghero** [comment]
![image](https://cloud.githubusercontent.com/assets/1644594/4919472/cadeca96-64fa-11e4-9a0b-86b137aabdbb.png)
这个没有什么问题啊

**Comment by codinghero** [comment]
这个没有什么问题啊 
![image](https://cloud.githubusercontent.com/assets/1644594/4919513/137fc106-64fb-11e4-8061-b4df6475d927.png)
