### ISSUE TITLE
修改course doc list 中的文件，使之也可以重传相应文件。

### ISSUE THREAD

**Issue by tristones** [tristones/branson#188]
![image](https://cloud.githubusercontent.com/assets/351457/4856819/2a137e08-60c3-11e4-8a3a-deec3fbb33f6.png)

类似其他部分的文件管理，每个文件条目有upload的link。能重传对应文件。

**Comment by codinghero** [comment]
这个不知道是不是理解错误，CourseDoc没有版本的概念，这个重传是删掉之前的重建一个同名的文件
