### ISSUE TITLE
training calendar 按月显示页面把两大分类的当月open course都显示在一起

### ISSUE THREAD

**Issue by tristones** [tristones/branson#21]
TrainingCalendarMonthView.aspx 这个页面按月显示的话，把两个大类的当月课程都显示在一个列表里。

如果是当月已经完成的课程，请把课程标题文字变成灰色。color:#aaa; 这个色值你看看。另外后面的状态要能正确显示该课程的状态。open的courses要能够enroll，已经结束的课程就是 completed。 具体样式参照 CourseList.aspx的右侧status区块。

![snip20131115_6](https://f.cloud.github.com/assets/351457/1549634/575b9d5a-4deb-11e3-8c2a-d0d8fe51ed3a.png)

**Comment by codinghero** [comment]
可以注册的课程，还没有点 ready to go 暂时状态为Pending
