### ISSUE TITLE
前台QA.aspx的图片上传功能只要保留local本地上传

### ISSUE THREAD

**Issue by tristones** [tristones/branson#23]
1.前台QA.aspx的图片上传功能只要保留local本地上传，去掉其他两项。
2.上传的图片，最大尺寸限定为宽高都是500px;

![snip20131115_10](https://f.cloud.github.com/assets/351457/1549661/1f3ef63c-4dec-11e3-8dde-269e4852f10c.png)

**Comment by tristones** [comment]
前台只保留local tab的问题已经修改，后端限定图片大小没改。另外现在默认头像显示的路径还是错误的，我在qa.aspx.cs已经改成相对路径了，不知是否还需要编译才能生效。

这个ueditor目前在IE8 下面有异常

![snip20131119_9](https://f.cloud.github.com/assets/351457/1572744/cd080198-5123-11e3-8ce0-b0413e189090.png)

**Comment by codinghero** [comment]
可能是js editor 变量和editor元素命名冲突，改为ed后在兼容模式不报错了，麻烦看看ie8,我没有
