### ISSUE TITLE
首页增加一个Monthly Training Plan的按钮，直接链接到当月的月度视图。

### ISSUE THREAD

**Issue by tristones** [tristones/branson#24]
首页增加一个Monthly Training Plan的按钮，直接链接到显示为当月的月度视图。
【首页的链接样式】我会先做好。新闻标题的长度估计也会有影响，可显示文字数要缩短一点。

![snip20131115_11](https://f.cloud.github.com/assets/351457/1549671/6f022acc-4dec-11e3-9891-f632b84e8316.png)

![snip20131115_12](https://f.cloud.github.com/assets/351457/1549672/7305c638-4dec-11e3-9b13-d3ccd6d3cf27.png)

**Comment by tristones** [comment]
修改的代码已经提交，首页新闻标题需要相应再截短一些。

![snip20131119_11](https://f.cloud.github.com/assets/351457/1573094/50a4d3a4-512a-11e3-8c6b-fed528379fe0.png)

**Comment by codinghero** [comment]
OK
