### ISSUE TITLE
Q&A reply question按钮无效。

### ISSUE THREAD

**Issue by tristones** [tristones/branson#32]
Q&A reply question (post comment) 按钮点击无效，新增问题的时候，该按钮可用。

![snip20131202_21](https://f.cloud.github.com/assets/351457/1652817/5ec965a6-5b22-11e3-884a-9ea65260c173.png)

**Comment by codinghero** [comment]
这个thread中有用户邮件地址不正确，已经在其他填写邮件地址入口添加验证，并捕获错误
