### ISSUE TITLE
console的课程编辑页面，course tag修改为可从下拉列表中选择

### ISSUE THREAD

**Issue by tristones** [tristones/branson#45]
console的课程编辑页面，course tag修改为可从下拉列表中选择。这个问题上次你好像说是可以的，不过我这边safari和firefox貌似没有下拉菜单可选。chrome没测试。你看看

![snip20131215_41](https://f.cloud.github.com/assets/351457/1750039/bf60d0ca-6563-11e3-8318-e56de9a4e28c.png)

**Comment by codinghero** [comment]
这个功能还能用，输入已经存在的tag就会弹出下拉菜单，现在改为双击文本框就弹出下拉菜单
