### ISSUE TITLE
user profile中，user可以un-enroll课程

### ISSUE THREAD

**Issue by tristones** [tristones/branson#51]
如果课程还没开始，用户可以在自己的my course history里面，选择un-enroll已经注册的课程。link就加在 view detail的右边。

注意课程开始后就不要显示该link。

![snip20140102_7](https://f.cloud.github.com/assets/351457/1831050/94a63598-7376-11e3-98da-4bf2f383111e.png)

**Comment by codinghero** [comment]
可以unenroll的条件是？
课程仍然pending,没有过registration close time/start time ?
