### ISSUE TITLE
Pending Application 增加Deny的link

### ISSUE THREAD

**Issue by tristones** [tristones/branson#52]
1，在Pending Application中的Manager Audit和HR Audit中，增加一个Deny的link。
可以以Manager或者HR的身份否决申请。

两者只要有一个deny,这个申请的状态就是denied，

2.因此相应的用户前台CourseHistory.aspx的相应位置的状态也显示为Denied.颜色框用红色表示。色值： #e11616

3，另外检查前台的Manager也需要可以Deny相应的课程申请。

4.一旦一个申请被Manager或者HR否决，则不显示在Pending Application列表中。

![snip20140102_8](https://f.cloud.github.com/assets/351457/1831061/53112cfe-7377-11e3-9234-deef0783d072.png)

![snip20140102_12](https://f.cloud.github.com/assets/351457/1831072/0da083da-7378-11e3-8b3a-110643d45e7a.png)

**Comment by codinghero** [comment]
denied课程是否可以unenroll
