### ISSUE TITLE
Statics Report / Output 输出，line manager, duration , presence status 为空值

### ISSUE THREAD

**Issue by tristones** [tristones/branson#63]
Statics Report / Output 输出，line manager , duration , presence status 为空值。这个应该是有值的。

![snip20140210_4](https://f.cloud.github.com/assets/351457/2122469/1da6c8ae-9211-11e3-87c6-f093ea457c3f.png)

**Comment by codinghero** [comment]
这里的line manager空白是因为数据库没有
duration用 Estimate Duration 代替吗？ 出席状态暂时没办法获知
不过如果上传了certificate一定是present了，没有也不一定没有present,所以导出记录没有这一项
