### ISSUE TITLE
output report 一直processing,没有结果显示。

### ISSUE THREAD

**Issue by tristones** [tristones/branson#73]
![cx81 1 2xstkljh3 4m5s](https://f.cloud.github.com/assets/351457/2255787/f3ff4d7c-9dfb-11e3-87a6-54e7f4a9afd0.jpg)

我在测试服务器有输出，没发现卡在Processing的问题。

**Comment by codinghero** [comment]
这次改了数据库结构，忘了和你说，让他们执行这个文件的sql就可以了
https://bitbucket.org/tristoneschen/branson_university/src/938429be18494cba9b40212248e44a0672d06c57/updatesql%2020140223.txt?at=master
