### ISSUE TITLE
不能传大文件

### ISSUE THREAD

**Issue by tristones** [tristones/branson#75]
找了个方案，不知道他们是否解决了。要IIS和asp.net版本，还没报给我。
估计是IIS7+

http://ajaxuploader.com/large-file-upload-iis-asp-net.htm

**Comment by codinghero** [comment]
如果无效请参照http://support.microsoft.com/kb/942074 修改

**Comment by codinghero** [comment]
http://www.cnblogs.com/henryhappier/archive/2010/09/20/1832098.html
