### ISSUE TITLE
Course Schedule的修改

### ISSUE THREAD

**Issue by tristones** [tristones/branson#85]
列表筛选年份，默认为当前年份，默认显示50条数据，按照Start Date的先后排序。另外是否可以在year旁边再加一个下拉菜单，过滤一下课程状态。菜单项包括 All,Completed,Pending,Open。 现在客户的反馈是想能单独看到Pending状态的课程。

![image](https://f.cloud.github.com/assets/351457/2318194/4b4538e2-a362-11e3-8231-94f47922d774.png)

点击Edit后，出现的人员列表中，HR右侧增加一列Presence Status,显示用户的出勤状态。Learner List改为默认显示50条数据。
![image](https://f.cloud.github.com/assets/351457/2318395/752a4144-a366-11e3-939a-3663676461c2.png)

点击Users后弹出的窗口中，在HR右侧增加一列 Presence Status,显示用户的出勤状态。

![image](https://f.cloud.github.com/assets/351457/2318205/7f52aa34-a362-11e3-817c-0d1d43021d74.png)

**Comment by codinghero** [comment]
适当控制一下甲方的欲望 :)

**Comment by tristones** [comment]
ok，应该快接近结束了。
