### ISSUE TITLE
后台Users列表，delete按钮执行前，增加一个弹窗确认动作

### ISSUE THREAD

**Issue by tristones** [tristones/branson#86]
后台Users列表，delete按钮执行前，增加一个弹窗确认动作，以免造成不需要的误删除操作。

![image](https://f.cloud.github.com/assets/351457/2318226/ede8721c-a362-11e3-9d71-187acf05e251.png)

**Comment by codinghero** [comment]
![image](https://f.cloud.github.com/assets/1644594/2322176/e6df6548-a3ad-11e3-877c-c92a6e3acdf6.png)
已经有了

**Comment by tristones** [comment]
我用safari测试了一下，没有弹窗。客户也来问了。你再确认一下

**Comment by codinghero** [comment]
线上的代码没有更新：![image](https://f.cloud.github.com/assets/1644594/2493860/def630a4-b2a9-11e3-979e-0b916f48ff6c.png)

最新代码 https://bitbucket.org/tristoneschen/branson_university/src/7e71b60ca9ced64e9f1429df153524a8d7dfa97c/Course.Website/Console/Users.aspx?at=master
