### ISSUE TITLE
statistics report / by user 问题

### ISSUE THREAD

**Issue by tristones** [tristones/branson#89]
statistics report / by user  选择user点击detail后的界面中。

Status中的Normal代表的是什么意思，从哪个数据项取值的？
Hours项目都是0，可以全部用estimate durations的值来显示，计算。

![image](https://f.cloud.github.com/assets/351457/2329579/47c595b2-a41c-11e3-91f4-d4bced02e68d.png)

**Comment by codinghero** [comment]
status是该用户在这个课程的学习情况，有  Normal = 0,
        Close = 1,
        Finish = 2,
        ReadyToGo = 3 这几个值可以选
