### ISSUE TITLE
后台新课程开课时出错

### ISSUE THREAD

**Issue by tristones** [tristones/branson#99]
![qr8o u_i _bdbjx vgk](https://f.cloud.github.com/assets/351457/2364254/349e966c-a667-11e3-8f5f-08963678efa8.jpg)

![kdlc 93ammx464z3kcmbc1](https://f.cloud.github.com/assets/351457/2364257/490e7f4a-a667-11e3-8a77-113eb5ed28e5.jpg)

**Comment by codinghero** [comment]
在数据库中删除t_course_sessions表中的enrollment列，该字段数据已经改成实时计算出
